import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="js" className="font-sans">
      <body className="font-mono antialiased">
        <div style={{ paddingTop: "10px" }}>{children}</div>
      </body>
    </html>
  );
}
